"""Tests for the GAAP Statement of Changes in Partners' Capital extractor.

Covers the deterministic extractor against:
  * Synthetic minimal SCPC text (unit tests for the parsing logic)
  * The real KPMG illustrative PDF (page 9 extracted as a focused fixture)
  * The real CohnReznick illustrative PDF (full document — exercises the
    multi-page SCPC-page locator and the whitespace-bug normalisation)

The KPMG and CohnReznick PDFs are public artifacts shipped under
``examples/real_world/``; they are skipped when not present so a slim
checkout still runs the test suite.
"""

from __future__ import annotations

from decimal import Decimal
from pathlib import Path

import pytest

from vc_statement_parser.extractors.gaap_scpc import (
    GaapScpcExtractor,
    _normalize_text,
    _parse_money,
    _parse_period,
)
from vc_statement_parser.models import FundAdministrator
from vc_statement_parser.parse import parse_statement
from vc_statement_parser.verification import verify

REAL_WORLD = Path(__file__).resolve().parent.parent / "examples" / "real_world"
KPMG_PDF = REAL_WORLD / "kpmg_pcap_p9.pdf"
COHNREZNICK_PDF = REAL_WORLD / "cohnreznick_pe_illustrative_2024.pdf"

FIXTURES_DIR = Path(__file__).resolve().parent.parent / "examples" / "fixtures"
SYNTH_SCPC = FIXTURES_DIR / "gaap_scpc_synthetic.pdf"


@pytest.fixture(scope="session")
def synthetic_scpc_pdf() -> Path:
    """Build (if missing) and return the synthetic GAAP SCPC fixture.

    Generated by `examples/fixtures/generate_gaap_scpc.py`. Caching is by file
    presence — this lets developers regenerate by deleting the .pdf.
    """
    if not SYNTH_SCPC.exists():
        from examples.fixtures.generate_gaap_scpc import (  # noqa: PLC0415
            render_gaap_scpc_pdf,
        )

        render_gaap_scpc_pdf(SYNTH_SCPC)
    return SYNTH_SCPC


# --------------------------------------------------------------------------- #
#   Pure unit tests on the parsing helpers
# --------------------------------------------------------------------------- #


class TestNormalizeText:
    def test_dollar_space_digit_collapses(self) -> None:
        assert "$4,900,000" in _normalize_text("$ 4 ,900,000")

    def test_kerning_split_on_first_comma_collapses(self) -> None:
        # CohnReznick: "9 18,000" → "918,000"
        assert "918,000" in _normalize_text("Capital contributions 2,000 9 18,000 9 20,000")

    def test_stray_leading_digit_collapses(self) -> None:
        # CohnReznick: stray "1" before "2,132,000"
        out = _normalize_text("Pro rata allocation 2,000 1 2,132,000 1 2,134,000")
        assert "12,132,000" in out
        assert "12,134,000" in out

    def test_kpmg_smashed_money_tokens_split(self) -> None:
        # KPMG: tightly-kerned "250,00024,750,00025,000,000" → 3 separate values
        out = _normalize_text("Capital contributions 250,00024,750,00025,000,000")
        assert "250,000 24,750,000 25,000,000" in out

    def test_does_not_split_inside_a_valid_number(self) -> None:
        # Must NOT corrupt "24,750,000" into "24,750 000" or similar
        out = _normalize_text("foo 24,750,000 bar")
        assert "24,750,000" in out
        assert "24,750 000" not in out


class TestParseMoney:
    def test_simple_value(self) -> None:
        assert _parse_money("$84,219,000") == Decimal("84219000")

    def test_parens_negative(self) -> None:
        assert _parse_money("(36,888,000)") == Decimal("-36888000")

    @pytest.mark.parametrize("dash", ["—", "–", "-"])  # noqa: RUF001  (em/en/hyphen variants in real PDFs)
    def test_dash_zero_placeholder(self, dash: str) -> None:
        assert _parse_money(dash) == Decimal("0")


class TestParsePeriod:
    def test_placeholder_year_substituted_with_2099(self) -> None:
        start, end, as_of = _parse_period("Year ended December 31, 20XX")
        assert end.year == 2099
        assert end.month == 12
        assert end.day == 31
        assert start == end.replace(year=2098, month=1, day=1)
        assert as_of == end

    def test_real_year(self) -> None:
        _, end, _ = _parse_period("Year Ended December 31, 2024")
        assert end.year == 2024


# --------------------------------------------------------------------------- #
#   End-to-end tests against the synthetic SCPC fixture (always runs)
# --------------------------------------------------------------------------- #


def test_synthetic_scpc_dispatcher_classifies_correctly(synthetic_scpc_pdf: Path) -> None:
    statement = parse_statement(synthetic_scpc_pdf, use_llm_fallback=False)
    assert statement.source_metadata.administrator is FundAdministrator.GAAP_SCPC


def test_synthetic_scpc_extracts_lp_column_correctly(synthetic_scpc_pdf: Path) -> None:
    statement = parse_statement(synthetic_scpc_pdf, use_llm_fallback=False)
    assert statement.lp_name == "All Limited Partners (Aggregate)"
    assert statement.fund_name == "Vintage Capital Partners V, L.P."
    assert statement.nav_beginning == Decimal("100000000")
    assert statement.contributions_period == Decimal("8000000")
    assert statement.distributions_period == Decimal("12000000")  # stored positive
    assert statement.realized_gain_loss == Decimal("4500000")
    assert statement.unrealized_gain_loss == Decimal("3000000")
    # Net investment loss + carried interest both bucket into partnership_expenses
    assert statement.partnership_expenses == Decimal("4000000")
    assert statement.management_fees == Decimal("0")
    assert statement.nav_ending == Decimal("99500000")


def test_synthetic_scpc_passes_nav_roll_forward(synthetic_scpc_pdf: Path) -> None:
    statement = parse_statement(synthetic_scpc_pdf, use_llm_fallback=False)
    report = verify(statement)
    assert report.passed, [r.name for r in report.failures]


def test_synthetic_scpc_skips_lp_only_invariants(synthetic_scpc_pdf: Path) -> None:
    """Commitment-identity / TVPI / DPI rely on LP-level fields the SCPC doesn't
    carry — verify() must skip them, not fail them."""
    statement = parse_statement(synthetic_scpc_pdf, use_llm_fallback=False)
    report = verify(statement)
    invariant_names = {r.name for r in report.results}
    assert "nav_roll_forward" in invariant_names
    assert "commitment_identity" not in invariant_names
    assert "tvpi_consistency" not in invariant_names
    assert "dpi_consistency" not in invariant_names


# --------------------------------------------------------------------------- #
#   Integration tests against the actual public PDFs
# --------------------------------------------------------------------------- #


@pytest.mark.skipif(not KPMG_PDF.exists(), reason="KPMG fixture not in checkout")
def test_kpmg_p9_parses_and_verifies() -> None:
    statement = parse_statement(KPMG_PDF, use_llm_fallback=False)
    assert statement.source_metadata.administrator is FundAdministrator.GAAP_SCPC
    assert statement.source_metadata.extractor == "deterministic.gaap_scpc"
    assert statement.lp_name == "All Limited Partners (Aggregate)"
    assert statement.fund_name == "Private Equity, L.P."
    # Spot-check the LP column figures from the actual document
    assert statement.nav_beginning == Decimal("682957000")
    assert statement.contributions_period == Decimal("24750000")
    assert statement.distributions_period == Decimal("36888000")  # stored positive
    assert statement.nav_ending == Decimal("703021000")
    # LP-only fields are absent in fund-level SCPC
    assert statement.commitment is None
    assert statement.paid_in_capital is None
    assert statement.unfunded_commitment is None
    # NAV roll-forward must balance to the cent.
    report = verify(statement)
    assert report.passed, [r.name for r in report.failures]
    invariant_names = {r.name for r in report.results}
    assert "nav_roll_forward" in invariant_names
    # No commitment data → commitment identity skipped
    assert "commitment_identity" not in invariant_names


@pytest.mark.skipif(not COHNREZNICK_PDF.exists(), reason="CohnReznick fixture not in checkout")
def test_cohnreznick_full_pdf_parses_and_verifies() -> None:
    statement = parse_statement(COHNREZNICK_PDF, use_llm_fallback=False)
    assert statement.source_metadata.administrator is FundAdministrator.GAAP_SCPC
    assert statement.fund_name == "Private Equity Fund, L.P."
    # Spot-check LP column from the actual SCPC page
    assert statement.nav_beginning == Decimal("71381000")
    assert statement.contributions_period == Decimal("918000")
    assert statement.distributions_period == Decimal("2097000")
    assert statement.nav_ending == Decimal("81334000")
    # The "Pro rata allocation" line bundles all P&L for CohnReznick — gets
    # routed into realized_gain_loss.
    assert statement.realized_gain_loss == Decimal("12132000")
    # Carried interest deduction shows up as partnership_expenses.
    assert statement.partnership_expenses == Decimal("1000000")
    report = verify(statement)
    assert report.passed, [r.name for r in report.failures]


@pytest.mark.skipif(not COHNREZNICK_PDF.exists(), reason="CohnReznick fixture not in checkout")
def test_dispatcher_finds_scpc_on_later_page_via_per_page_text() -> None:
    """Regression for the per_page_text dispatcher path.

    The CohnReznick PDF has 29 pages and the SCPC sits on page 9. Without
    per-page header scanning, only the cover page is examined and the document
    looks like an `unknown` administrator.
    """
    statement = parse_statement(COHNREZNICK_PDF, use_llm_fallback=False)
    assert statement.source_metadata.administrator is FundAdministrator.GAAP_SCPC


# --------------------------------------------------------------------------- #
#   Negative tests — extractor refuses unrelated documents
# --------------------------------------------------------------------------- #


def test_extract_raises_when_no_scpc_page_present() -> None:
    """Documents matched by the dispatcher but missing the SCPC data row
    (e.g. a TOC-only mention) must not be silently parsed into garbage."""
    extractor = GaapScpcExtractor()
    with pytest.raises(ValueError, match="could not locate the SCPC page"):
        extractor.extract(
            source=Path("/dev/null"),
            text="Statement of Changes in Partners' Capital is mentioned here only.",
            per_page_text=[
                "Cover page — index — references Statement of Changes in Partners' Capital",
                "Other unrelated page",
            ],
        )


def test_missing_required_field_error_lists_what_was_found() -> None:
    """Error messages must surface enough context to debug a parsing failure.

    A page that has the SCPC heading + 'beginning of year' anchor but lacks
    a parseable end-of-year row should fail loudly AND tell the operator
    which categories DID match, so the regex patterns can be extended.
    """
    extractor = GaapScpcExtractor()
    page = (
        "Synthetic Fund, L.P.\n"
        "Statement of Changes in Partners' Capital\n"
        "Year ended December 31, 2024\n"
        "Partners' capital, beginning of year $100,000 $1,000,000 $1,100,000\n"
        "Capital contributions $5,000 $50,000 $55,000\n"
        # No "Partners' capital, end of year" row here.
    )
    with pytest.raises(ValueError, match=r"missing required field\(s\).*nav_ending") as exc:
        extractor.extract(source=Path("/dev/null"), text=page, per_page_text=[page])
    msg = str(exc.value)
    # The message should also reference the categories that DID match,
    # so an operator can see what's already wired and what's missing.
    assert "nav_beginning" in msg
    assert "contributions_period" in msg


def test_confidence_lower_for_pro_rata_allocation_path(synthetic_scpc_pdf: Path) -> None:
    """KPMG-style broken-out P&L rows produce higher confidence than the
    CohnReznick-style 'Pro rata allocation' compact path."""
    statement = parse_statement(synthetic_scpc_pdf, use_llm_fallback=False)
    # Synthetic fixture uses the broken-out KPMG path, so high-confidence.
    assert statement.source_metadata.parse_confidence == 0.85


@pytest.mark.skipif(not COHNREZNICK_PDF.exists(), reason="CohnReznick fixture not in checkout")
def test_cohnreznick_uses_lower_confidence_due_to_pro_rata_path() -> None:
    """The actual CohnReznick PDF takes the compact path → lower confidence."""
    statement = parse_statement(COHNREZNICK_PDF, use_llm_fallback=False)
    assert statement.source_metadata.parse_confidence == 0.70
